### ISSUE TITLE
file names within test cases

### ISSUE THREAD

**Issue by marcusrosenblatt** [PEtab-dev/petab_test_suite#12]
Hi,

at the moment, we have "_model.tsv", "_parameters.tsv", "_observables.tsv" as file names for the test cases. Is there a reason why we not use the ones as in the benchmark collection? So we would e.g. have "model_0001.tsv" and "experimentalCondition_0001.tsv" with "0001" being the model name.

This would make it easier to write consistent import/export functions.

Best,
Marcus

**Comment by yannikschaelte** [comment]
Hi Marcus,

we can think about changing the default names, but in the past there were several concerns with having such naming conventions. Thus, we have the yaml files, which are also generated in the cases folders. Would it be possible for you to extract the files from the yaml files? There might be a specific "supports yaml" test coming too ...

**Comment by marcusrosenblatt** [comment]
Ah right. I just saw it!

Then we will pull out the names from there.
