### ISSUE TITLE
#0007 tests multiple settings at once

### ISSUE THREAD

**Issue by refisch** [PEtab-dev/petab_test_suite#20]
Hi all,
in addition to #11 we would suggest to split this test case in

7a) two data points, one on linear, one on log10 scale
7b) two data points, one on linear, one on log scale.

This would make transparent that d2d natively supports log10 trafos, but not natural logithm trafos (although this is doable in principle).

Best,
Lukas

**Comment by dweindl** [comment]
Hi Lukas, thanks for your suggestions. Fine for me to split it. (Although I would not go for a/b, but just append a new test case) @yannikschaelte ?

**Comment by yannikschaelte** [comment]
I will separate this into two test cases, agreed!

**Comment by yannikschaelte** [comment]
@refisch this has been separated now to tests 0007 and 0016. hope it works!
