### ISSUE TITLE
Symlink not working for PEtab tests

### ISSUE THREAD

**Issue by dilpath** [PEtab-dev/petab_test_suite#38]
Example failure
https://github.com/PEtab-dev/PEtab/runs/1622376739#step:6:63

Tries to access this file
https://raw.githubusercontent.com/PEtab-dev/petab_test_suite/master/cases/0001/_0001.yaml

I guess the symlink `cases -> petabtests/cases` isn't working correctly? Switched PEtab to use
https://raw.githubusercontent.com/PEtab-dev/petab_test_suite/master/petabtests/cases/0001/_0001.yaml
for now, which works: https://github.com/PEtab-dev/PEtab/pull/493/commits/aaf16904484630164b9ce60036644c7700ba2ac4

**Comment by dweindl** [comment]
Is there still a problem? Not sure what to do about this. The symlink works after cloning the the repository (if the the OS supports symlinks). This was mostly intended for people not using the included python library.

**Comment by dilpath** [comment]
I think it's an expected problem and this issue can be closed: one should avoid accessing the cases from github.com via the symlink, since it will 404.

I think it could make sense to just move `petabtests/cases` to `cases` (so, out of the Python code directory), is there a reason to not do this? Fine to leave as is if it will break downstream things.

**Comment by dweindl** [comment]
>  one should avoid accessing the cases from github.com via the symlink, since it will 404.

right.

> I think it could make sense to just move `petabtests/cases` to `cases` (so, out of the Python code directory), is there a reason to not do this? Fine to leave as is if it will break downstream things.

Doing that will create problems with including the test cases in the python package afair.
