### ISSUE TITLE
Performance criterion

### ISSUE THREAD

**Issue by yannikschaelte** [PEtab-dev/petab_test_suite#5]
What exactly should be the criterion whether a tool supports a feature, i.e. that a test case passes? We have simulations tables, chi2 and llh values. However, not all tools support chi2 or llh values, or to extract the simulations. One thing to do would be to consider it passed if any of the three values fits, and to add an additional note, e.g. "tool does not support likelihoods". Other ideas?

**Comment by marcusrosenblatt** [comment]
We discussed this topic this morning with Svenja and Adrian. The majority of the three of us is in favour of checking all the three criteria. At least for D2D and dMod, it should not be so much effort to extend the existing test functions.

I like the idea with the additional note. The test would then result in "Passed" with a side note which of the three criteria were checked.

**Comment by dweindl** [comment]
I provisionally started with this overview here: https://github.com/PEtab-dev/PEtab/tree/develop#petab-features-supported-in-different-tools

This shows status for simulation, chi2 and llh separately. Requiring all of them would be a bit unfair, as some tools may simply not compute any likelihoods although they may support all other features.

**Comment by yannikschaelte** [comment]
implemented as discussed in petab.
