### ISSUE TITLE
bug in test model 0006!?

### ISSUE THREAD

**Issue by marcusrosenblatt** [PEtab-dev/petab_test_suite#9]
Hi,

maybe I am missing sth., but I think the solution value (e.g. chi^2) for model 0006 is not correct. The result suggests that the data in the measurement file has to be scaled by the observable parameters (once 10 and once 15). In my understanding the observable parameters shall be used for the observables only and data should already be on the right scale (atm it is 1 at t=0, should be 10). 

Most likely data points have just to be adjusted accordingly in the measurement file.

Btw: Do we actually have benchmark models where sth like this is appearing? Different scaling factors for one and the same combination of simulationConditionID and observables?

Best,
Marcus

**Comment by yannikschaelte** [comment]
Hi Marcus,

yes you are right, there seems to be a bug: We forgot to apply the scaling to the simulations (=observables). The measurements should be fine (you are right, the observable parameters should only be applied to the observables, not the measurements), but then the chi2 value needs to be adjusted.

I will fix this tomorrow. There definitely are cases in the benchmark collection where timepoint specific overrides occur, but I do not know which ones that were (@LeonardSchmiester ?). This can be circumvented by simply creating separate conditions in such cases though.

Yannik

**Comment by LeonardSchmiester** [comment]
There were some, e.g. Isensee. I adapted most of them by adding new observables to circumvent the timepoint specific overrides, as amici cant handle that yet. But in the Initial Implementation there were several models.

**Comment by marcusrosenblatt** [comment]
Ok, I see. dMod is not able to handle this either. Only with additional conditions as already suggested.

**Comment by yannikschaelte** [comment]
@marcusrosenblatt this is addressed in #10
